"""Structural tests for the Plan 01-05 Compose contract.

This file is the FAST structural gate (parses compose.yaml + reads infra files
+ asserts the expected service shape). The actual end-to-end `docker compose
up` gate lives in `just compose-smoke` and runs in CI only — too slow for
per-test feedback (~30-60s for a full clean boot + sync + teardown).

What's tested here:
  - services/fake-discogsography/{Dockerfile, server.py, seed.yaml} exist with
    the right shape (server.py imports the canonical module from
    `gruvax._internal.fake_discogsography` — D-15 single-module mandate).
  - No copy of fake_discogsography.py lives under services/ (D-15: NO
    duplication, NO drift guard).
  - seed.yaml has >= 2900 releases (generated by Plan 01-00's `just
    regen-synth-data`; this plan does NOT regenerate).
  - compose.yaml has the fake-discogsography service + init-sync one-shot
    service.
  - init-sync command contains the D-16-mandated idempotency precheck
    (`SELECT COUNT(*) FROM gruvax.profile_collection ... skipping initial
    sync`).
  - api service depends_on adds fake-discogsography healthy.
  - justfile has the `compose-smoke` recipe.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
import yaml


# Repo root resolved relative to this test file.
REPO_ROOT = Path(__file__).resolve().parents[2]

SERVICES_FAKE_DIR = REPO_ROOT / "services" / "fake-discogsography"


def _load_compose() -> dict[str, Any]:
    compose_path = REPO_ROOT / "compose.yaml"
    assert compose_path.exists(), f"compose.yaml missing at {compose_path}"
    data: dict[str, Any] = yaml.safe_load(compose_path.read_text())
    return data


# ── services/fake-discogsography/ shape (D-15: single-module mandate) ────────


def test_fake_discogsography_dockerfile_present() -> None:
    """Dockerfile exists and is non-empty."""
    dockerfile = SERVICES_FAKE_DIR / "Dockerfile"
    assert dockerfile.exists(), f"Missing {dockerfile}"
    content = dockerfile.read_text()
    assert content.strip(), "Dockerfile is empty"


def test_fake_discogsography_server_imports_canonical_module() -> None:
    """server.py MUST import from the canonical module per D-15.

    No copy of fake_discogsography.py body in services/ — the Compose sibling
    imports `gruvax._internal.fake_discogsography.create_fake_app` directly.
    The Dockerfile installs the gruvax package so the import resolves at
    runtime.
    """
    server_py = SERVICES_FAKE_DIR / "server.py"
    assert server_py.exists(), f"Missing {server_py}"
    content = server_py.read_text()
    assert "from gruvax._internal.fake_discogsography import" in content, (
        "server.py must import the canonical module per D-15: "
        "`from gruvax._internal.fake_discogsography import create_fake_app`"
    )
    # The canonical create_fake_app symbol must be the imported one (not a
    # local re-implementation).
    assert "create_fake_app" in content, "server.py must reference create_fake_app"


def test_no_duplicate_fake_module_in_services_dir() -> None:
    """D-15 grep gate: NO `class FakeDiscogsography` or duplicate `create_fake_app`
    definition under services/fake-discogsography/.

    This guards against a future contributor copy-pasting the canonical module
    body into the services/ directory ("drift" risk addressed by D-15).
    """
    forbidden = SERVICES_FAKE_DIR / "fake_discogsography.py"
    assert not forbidden.exists(), (
        f"D-15 violation: a copy of fake_discogsography.py exists at {forbidden}. "
        "The canonical module is src/gruvax/_internal/fake_discogsography.py; "
        "services/fake-discogsography/server.py imports it via `from "
        "gruvax._internal.fake_discogsography import create_fake_app`."
    )
    # Also grep the rest of the services/ tree for a `def create_fake_app` —
    # only the server.py import line should reference the name.
    for path in SERVICES_FAKE_DIR.rglob("*.py"):
        if path.name == "server.py":
            continue
        text = path.read_text()
        assert "def create_fake_app" not in text, (
            f"D-15 violation: {path} defines create_fake_app locally — the "
            "canonical module owns this definition."
        )


def test_seed_yaml_has_at_least_2900_releases() -> None:
    """seed.yaml ships with the ~3000-release synthetic dataset (Plan 01-00).

    Plan 05 does NOT regenerate the seed — it's the same source-of-truth as
    tests/fixtures/synth_profile_collection.sql (per Blocker #4 RESOLUTION).
    """
    seed_path = SERVICES_FAKE_DIR / "seed.yaml"
    assert seed_path.exists(), f"Missing {seed_path}"
    data = yaml.safe_load(seed_path.read_text())
    releases = data.get("releases")
    assert releases is not None, "seed.yaml missing top-level 'releases' key"
    assert len(releases) >= 2900, (
        f"seed.yaml should have >= 2900 releases (Plan 01-00 generates ~3000); got {len(releases)}"
    )


# ── compose.yaml service blocks ──────────────────────────────────────────────


def test_compose_has_fake_discogsography_service() -> None:
    """fake-discogsography sibling service block exists with the expected shape."""
    compose = _load_compose()
    services = compose.get("services", {})
    assert "fake-discogsography" in services, (
        f"compose.yaml missing fake-discogsography service. Have: {list(services)}"
    )
    svc = services["fake-discogsography"]
    # Build context must be repo root so the gruvax package is in scope.
    assert "build" in svc, "fake-discogsography needs a build: block"
    build = svc["build"]
    assert build.get("context") == ".", (
        f"fake-discogsography build.context must be repo root '.', got {build.get('context')!r}"
    )
    assert "Dockerfile" in (build.get("dockerfile") or ""), (
        f"fake-discogsography build.dockerfile should reference Dockerfile, "
        f"got {build.get('dockerfile')!r}"
    )
    # Healthcheck — calls the contract endpoint with the dev seed token.
    healthcheck = svc.get("healthcheck", {})
    test_cmd = healthcheck.get("test")
    assert test_cmd is not None, "fake-discogsography missing healthcheck"
    test_str = " ".join(test_cmd) if isinstance(test_cmd, list) else str(test_cmd)
    assert "/api/user/collection" in test_str, (
        "healthcheck must hit /api/user/collection per the contract"
    )
    # Internal-only network — no host port mapping (T-01-fake-svc-exposure).
    assert "ports" not in svc, (
        "fake-discogsography must NOT bind host ports — internal compose "
        "network only per T-01-fake-svc-exposure"
    )
    assert "internal" in svc.get("networks", []), (
        "fake-discogsography must attach to the internal network"
    )


def test_compose_api_depends_on_fake_discogsography_healthy() -> None:
    """api service depends_on adds fake-discogsography healthy condition."""
    compose = _load_compose()
    api = compose["services"]["api"]
    depends = api.get("depends_on", {})
    assert "fake-discogsography" in depends, (
        f"api.depends_on must include fake-discogsography. Got: {list(depends)}"
    )
    cond = depends["fake-discogsography"]
    # Compose long-form: { condition: service_healthy }
    if isinstance(cond, dict):
        assert cond.get("condition") == "service_healthy", (
            f"api must depend on fake-discogsography service_healthy, got {cond!r}"
        )
    else:
        pytest.fail(f"api.depends_on.fake-discogsography must be long-form dict, got {cond!r}")


def test_compose_has_init_sync_service() -> None:
    """init-sync one-shot service exists with the right shape per D-16."""
    compose = _load_compose()
    services = compose["services"]
    assert "init-sync" in services, (
        f"compose.yaml missing init-sync service. Have: {list(services)}"
    )
    svc = services["init-sync"]
    # restart: "no" — one-shot
    assert svc.get("restart") == "no", (
        f"init-sync must have restart: 'no' (one-shot), got {svc.get('restart')!r}"
    )
    # Depends on api + fake-discogsography healthy
    depends = svc.get("depends_on", {})
    for upstream in ("api", "fake-discogsography"):
        assert upstream in depends, f"init-sync.depends_on must include {upstream}"
        cond = depends[upstream]
        assert isinstance(cond, dict) and cond.get("condition") == "service_healthy", (
            f"init-sync must depend on {upstream} service_healthy, got {cond!r}"
        )


def test_init_sync_command_contains_d16_idempotency_precheck() -> None:
    """init-sync command MUST contain the D-16-mandated precheck.

    Per D-16 verbatim: `idempotent — skips if profile_collection is already
    populated for the default profile`. The precheck implementation is a psql
    SELECT COUNT(*) gated on profile_id = the default UUID; if > 0, the
    container exits 0 with a "skipping" log line; else it runs gruvax-sync.
    """
    compose = _load_compose()
    svc = compose["services"]["init-sync"]
    # The command is typically a list (with sh -c entrypoint) or a single
    # string. Flatten to one searchable string.
    command = svc.get("command")
    cmd_str = " ".join(str(c) for c in command) if isinstance(command, list) else str(command or "")
    assert "SELECT COUNT(*)" in cmd_str, (
        "init-sync.command must contain the D-16 idempotency precheck "
        "(SELECT COUNT(*) FROM gruvax.profile_collection WHERE profile_id = ...)"
    )
    assert "gruvax.profile_collection" in cmd_str, (
        "init-sync.command precheck must target gruvax.profile_collection"
    )
    assert "00000000-0000-0000-0000-000000000001" in cmd_str, (
        "init-sync.command precheck must reference the default profile UUID "
        "(00000000-0000-0000-0000-000000000001)"
    )
    assert "skipping initial sync" in cmd_str, (
        "init-sync.command must log 'skipping initial sync' when "
        "profile_collection is already populated (D-16 verbatim)"
    )
    assert "gruvax-sync" in cmd_str, (
        "init-sync.command must invoke gruvax-sync when profile_collection is empty"
    )


def test_init_sync_admin_pin_env_required() -> None:
    """init-sync must require GRUVAX_ADMIN_PIN — never silently boot without it.

    Per T-01-init-sync-pin: compose uses `${GRUVAX_ADMIN_PIN:?...}` substitution
    so compose-up fails clearly if the variable is missing.
    """
    compose = _load_compose()
    svc = compose["services"]["init-sync"]
    env = svc.get("environment", {})
    pin = env.get("GRUVAX_ADMIN_PIN")
    assert pin is not None, "init-sync environment must declare GRUVAX_ADMIN_PIN"
    assert ":?" in str(pin), (
        f"init-sync GRUVAX_ADMIN_PIN must use '${{GRUVAX_ADMIN_PIN:?...}}' "
        f"substitution to fail compose-up when unset. Got: {pin!r}"
    )


# ── justfile recipe ──────────────────────────────────────────────────────────


def test_justfile_has_compose_smoke_recipe() -> None:
    """justfile declares the `compose-smoke` recipe (CI gate per Blocker #2)."""
    justfile = REPO_ROOT / "justfile"
    assert justfile.exists()
    content = justfile.read_text()
    assert "compose-smoke" in content, (
        "justfile must declare a `compose-smoke` recipe per Blocker #2 RESOLUTION"
    )
    # The recipe should bring up the stack, assert init-sync exits 0, and tear down.
    assert "docker compose up" in content, "compose-smoke recipe must call docker compose up"
    assert "docker compose down" in content, (
        "compose-smoke recipe must tear down the stack at the end"
    )
