"""Compose-sibling fake discogsography (Plan 01-05, D-15).

This script is the entry point for the `fake-discogsography` Compose service.
It imports the canonical fake-discogsography FastAPI factory from
``gruvax._internal.fake_discogsography`` (the single source of truth — D-15
mandate: NO copy of the canonical module body lives under services/, and there
is intentionally NO ``just sync-fake`` drift guard).

The seed payload is loaded from the sibling ``seed.yaml`` (generated by Plan
01-00's ``just regen-synth-data`` — the same source-of-truth that populates
``tests/fixtures/synth_profile_collection.sql`` for SQL-fixture-based tests).

The module-level ``app`` symbol is what uvicorn binds to:

    uvicorn server:app --host 0.0.0.0 --port 8004

The ``user_id`` in every response envelope is fixed to the dev-only sentinel
``dddddddd-dddd-dddd-dddd-dddddddddddd`` — a VALID UUID. The column
``gruvax.profiles.discogsography_user_id`` is UUID-typed (migration 0009), so the
prior ``00000000-0000-0000-0000-DEFAULTDEVUSER`` form was not valid hex and broke
the ``connect_pat`` ``::uuid`` cast on the compose stack. Plan 04's
``gruvax-set-pat`` test sync validates this against
``gruvax.profiles.discogsography_user_id`` when the operator rotates the PAT.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from gruvax._internal.fake_discogsography import create_fake_app


_SEED_PATH = Path(__file__).parent / "seed.yaml"
_seed = yaml.safe_load(_SEED_PATH.read_text())["releases"]

# Module-level FastAPI app — uvicorn binds to `server:app`.
# user_id is a fixed dev sentinel; production uses the real discogsography
# service, never this container.
app = create_fake_app(seed=_seed, user_id="dddddddd-dddd-dddd-dddd-dddddddddddd")
