"""GET /api/version — build metadata for GRUVAX.

Public endpoint (LAN-only box). Returns only:
  - ``git_sha``:        git commit SHA baked in at Docker build time.
  - ``build_timestamp``: ISO-8601 UTC string of the build moment.
  - ``environment``:    deployment environment (development / production).

Security (T-08-01): Only these three keys are returned.  No settings
fields, DSN, session secrets, PIN hashes, or environment variables are
exposed.  The ``try/except ImportError`` fallback handles the dev case
where ``_version.py`` has not yet been generated by ``just build-version``
or Docker.
"""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import JSONResponse


try:
    from gruvax._version import BUILD_TIMESTAMP, ENVIRONMENT, GIT_SHA
except ImportError:
    GIT_SHA = "dev"
    BUILD_TIMESTAMP = "unknown"
    ENVIRONMENT = "development"

router = APIRouter(tags=["version"])


@router.get("/version")
async def get_version() -> JSONResponse:
    """Return build metadata (public, unauthenticated).

    Returns:
        JSON object with ``git_sha``, ``build_timestamp``, ``environment``.
        No secrets or internal configuration values are exposed.
    """
    return JSONResponse(
        {
            "git_sha": GIT_SHA,
            "build_timestamp": BUILD_TIMESTAMP,
            "environment": ENVIRONMENT,
        }
    )
