-- Synthetic profile_collection seed (committed; PII-free).
--
-- Targets gruvax.profile_collection for the default profile UUID
-- (00000000-0000-0000-0000-000000000001). Replaces the v1.0
-- fixtures/synth_collection.sql (now at tests/fixtures/legacy/) per D-17.
--
-- This file is GENERATED by tests/fixtures/generate_synth_data.py.
-- Regenerate via: just regen-synth-data
--
-- Shape-variety contract (preserved from v1.0 synth_collection.sql header):
--   - alpha-prefix + digits: BLP 4001..4020, ECM 1001..1015
--   - multi-prefix within one label: "Blue Note" has BLP + BST prefixes
--   - mixed separators within one label: KC 32731 and KC-32732
--   - pure numeric: 32731..32740
--   - multi-value catalog (comma): BLP-100, BST-200
--   - ~50 singleton labels
--
-- Idempotent: TRUNCATE + INSERT can be re-run; profile seed uses ON CONFLICT DO NOTHING.

INSERT INTO gruvax.profiles (id, display_name, app_token_encrypted, app_token_revoked)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default', '\x'::bytea, TRUE)
ON CONFLICT (id) DO NOTHING;

TRUNCATE gruvax.profile_collection RESTART IDENTITY CASCADE;

-- BEGIN GENERATED INSERTS (populated by tests/fixtures/generate_synth_data.py)
-- (Wave 0 scaffold: rows are empty. Plan 06 Task 1 regenerates with full ~3000 rows.)
-- END GENERATED INSERTS
